=== 4850-DN/XML-Lab/data/schedule.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
DTD for master.xml
Structured for days, timeslots, and courses
-->

<!-- Timetable element contains days, timeslots, and courses -->
<!ELEMENT timetable (days|timeslots|courses)>

<!-- Days element contains days of the week -->
<!ELEMENT days (day)>

<!-- Timeslots element contains timeslots of the week -->
<!ELEMENT timeslots (timeslot)>

<!-- Courses element contains courses of the week -->
<!ELEMENT courses (course)>

<!-- Day element contains timeslot, course, and booking -->
<!ELEMENT day (timeslot|course|booking)>
<!-- Day attributes contains days of the week -->
<!ATTLIST day
    weekday (MON|TUE|WED|THU|FRI) #REQUIRED
  >

<!-- Timeslot element contains timetable data -->
<!ELEMENT timeslot (course|day)>
<!-- Timeslot attributes contains start and end time -->
<!ATTLIST timeslot
    start CDATA #REQUIRED
    end CDATA #REQUIRED
  >

<!-- Course element contains booking or timeslot -->
<!ELEMENT course (booking|timeslot)>
<!-- Course attribute contains course code -->
<!ATTLIST course
    code CDATA #REQUIRED
  >

<!-- Booking element contains room and instructor -->
<!ELEMENT booking (room|instructor)>

<!-- Room element contains room number -->
<!ELEMENT room (#PCDATA)>

<!-- Instructor element contains instructor name -->
<!ELEMENT instructor (#PCDATA)>

=== 4850-DN/XML-Lab/data/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "schedule.dtd">
<!--
Format of courses.xml
<course code="" type="">
	<timeslot start="" end="">
		<day weekday="">
			<booking>
				<room></room>
				<instructor></instructor>
			</booking>
		</day>
	</timeslot>
</course>
-->
<timetable>
	<courses>
		<course code="4910" type="Lec">
			<timeslot start="15:30" end="16:20">
				<day weekday="MON">
					<booking>
						<room>sw1-2005</room>
						<instructor>richard chau</instructor>
					</booking>
				</day>
			</timeslot>
			<timeslot start="09:30" end="10:20">
				<day weekday="THU">
					<booking>
						<room>sw5-1840</room>
						<instructor>richard chau</instructor>
					</booking>
				</day>
			</timeslot>
		</course>
		
		<course code="4910" type="Lab">
			<timeslot start="15:30" end="16:20">
				<day weekday="THU">
					<booking>
						<room>se12-306</room>
						<instructor>richard chau</instructor>
					</booking>
				</day>
			</timeslot>
		</course>
		
		<course code="4850" type="Lab">
			<timeslot start="13:30" end="15:20">
				<day weekday="THU">
					<booking>
						<room>se12-308</room>
						<instructor>james parry</instructor>
					</booking>
				</day>
			</timeslot>
		</course>
		
		<course code="4660" type="Lec">
			<timeslot start="08:30" end="10:20">
				<day weekday="FRI">
					<booking>
						<room>sw9-206</room>
						<instructor>steve fabiszewski</instructor>
					</booking>
				</day>
			</timeslot>
		</course>
		
		<course code="4660" type="Lab">
			<timeslot start="13:30" end="15:20">
				<day weekday="FRI">
					<booking>
						<room>se12-306</room>
						<instructor>steve fabiszewski</instructor>
					</booking>
				</day>
			</timeslot>
		</course>

		<course code="4770" type="Lab">
			<timeslot start="10:30" end="12:20">
				<day weekday="FRI">
					<booking>
						<room>se12-306</room>
						<instructor>trevor lord</instructor>
					</booking>
				</day>
			</timeslot>
		</course>
	</courses>
</timetable>

=== 4850-DN/XML-Lab/data/timeslots.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "schedule.dtd">

<timetable>
	<timeslots>
		<timeslot start="12:30" end="14:20">
			<day weekday="WED">
				<course code="4850">
					<booking>
						<room>se6-207</room>
						<instructor>jim</instructor>
					</booking>
				</course>
			</day>
		</timeslot>
	</timeslots>
</timetable>
